### ISSUE TITLE
Explicit curve format support

### ISSUE THREAD

**Issue by teamworktf** [warner/python-ecdsa#66] opened 2017-02-24 10:55 UTC
Why does this not work, I used the exact same commands as in the openssl example. It's a secp224r1 curve.
```
-----BEGIN PUBLIC KEY-----
MIIBKjCB6wYHKoZIzj0CATCB3wIBATAoBgcqhkjOPQEBAh0A////////////////
/////wAAAAAAAAAAAAAAATBTBBz////////////////////+///////////////+
BBy0BQqFDASzq/VBMlZQRLC317/YuicLOUMjVf+0AxUAvXE0R5nVx/zcRbWfo7mr
j2qUi8UEOQS3Dgy9a7S/fzITkLlKA8HTVsIRIjQygNYRXB0hvTdjiLX3I/tMIt/m
zUN1oFoHR2RE1YGZhQB+NAIdAP//////////////////FqLguPA+E90pRVxcKj0C
AQEDOgAEdJYkwBFKz9nru4MVvMeD4DE9KuLx/tMxUOYKZFFMBHxstBpzCjO9+PTu
sOegeFgd/zM7xayysyM=
-----END PUBLIC KEY-----
```

`vk = VerifyingKey.from_pem(open(config['public_key']).read())` yields:

```
Traceback (most recent call last):
  File "./verify_signature.py", line 83, in <module>
    verifySignature('109.230.215.208', 27145, 'v1:4:redsun:24-04-2018:MDwCHEP6WloptmfHX+ESBMpn38/hl1NJs4LfQtbX/BUCHGIhcUQbKKmNKMtk8/qvo1jPNpiEtwWbE9JZYA4=')
  File "./verify_signature.py", line 72, in verifySignature
    vk = VerifyingKey.from_pem(open(config['public_key']).read())
  File "/usr/local/lib/python3.4/dist-packages/ecdsa/keys.py", line 52, in from_pem
    return klass.from_der(der.unpem(string))
  File "/usr/local/lib/python3.4/dist-packages/ecdsa/keys.py", line 64, in from_der
    oid_curve, empty = der.remove_object(rest)
  File "/usr/local/lib/python3.4/dist-packages/ecdsa/der.py", line 82, in remove_object
    raise UnexpectedDER("wanted object (0x06), got 0x%02x" % n)
ecdsa.der.UnexpectedDER: wanted object (0x06), got 0x30
```

Edit: I was talking about these openssl commands: https://github.com/warner/python-ecdsa#openssl-compatibility

**Comment by tomato42** [comment] 2017-02-27 14:17
the private key specifies the curve parameters explicitly, not though a name:

```
$ openssl asn1parse -in a.pem
    0:d=0  hl=4 l= 298 cons: SEQUENCE          
    4:d=1  hl=3 l= 235 cons: SEQUENCE          
    7:d=2  hl=2 l=   7 prim: OBJECT            :id-ecPublicKey
   16:d=2  hl=3 l= 223 cons: SEQUENCE          
   19:d=3  hl=2 l=   1 prim: INTEGER           :01
   22:d=3  hl=2 l=  40 cons: SEQUENCE          
   24:d=4  hl=2 l=   7 prim: OBJECT            :prime-field
   33:d=4  hl=2 l=  29 prim: INTEGER           :FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000000000000000000001
   64:d=3  hl=2 l=  83 cons: SEQUENCE          
   66:d=4  hl=2 l=  28 prim: OCTET STRING      [HEX DUMP]:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFE
   96:d=4  hl=2 l=  28 prim: OCTET STRING      [HEX DUMP]:B4050A850C04B3ABF54132565044B0B7D7BFD8BA270B39432355FFB4
  126:d=4  hl=2 l=  21 prim: BIT STRING        
  149:d=3  hl=2 l=  57 prim: OCTET STRING      [HEX DUMP]:04B70E0CBD6BB4BF7F321390B94A03C1D356C21122343280D6115C1D21BD376388B5F723FB4C22DFE6CD4375A05A07476444D5819985007E34
  208:d=3  hl=2 l=  29 prim: INTEGER           :FFFFFFFFFFFFFFFFFFFFFFFFFFFF16A2E0B8F03E13DD29455C5C2A3D
  239:d=3  hl=2 l=   1 prim: INTEGER           :01
  242:d=1  hl=2 l=  58 prim: BIT STRING
```

I don't think this format is supported by python-ecdsa


while parameters specified by name can be generated like this:
```
$ openssl ecparam -name secp224r1 -out p224.pem
$ openssl ecparam -in p224.pem -out c.pem -genkey -noout
```
and look like this:
```
$ openssl asn1parse -in c.pem 
    0:d=0  hl=2 l= 104 cons: SEQUENCE          
    2:d=1  hl=2 l=   1 prim: INTEGER           :01
    5:d=1  hl=2 l=  28 prim: OCTET STRING      [HEX DUMP]:293853057472B37BBFEFCFA9802AFE844F74925070CD836E41395235
   35:d=1  hl=2 l=   7 cons: cont [ 0 ]        
   37:d=2  hl=2 l=   5 prim: OBJECT            :secp224r1
   44:d=1  hl=2 l=  60 cons: cont [ 1 ]        
   46:d=2  hl=2 l=  58 prim: BIT STRING
```

**Comment by tomato42** [comment] 2019-09-29 11:29
duplicate of #39

**Closed** 2019-09-29 11:30 UTC
Labels: feature, help wanted
