### ISSUE TITLE
Compressed public key to uncompressed

### ISSUE THREAD

**Issue by NotStatilko** [warner/python-ecdsa#121] opened 2019-09-29 17:05 UTC
Hello! How can I get the full public key from compressed?  Couldn't find an exact answer.

For example from this **X** point (**secp256k1**)

```
0329908081367423272746086114569421970207888665320998202915346633185016778189308
```
Thanks!

**Comment by tomato42** [comment] 2019-09-29 17:44
It's not supported yet, see proposed PR #118 

duplicate of #1

**Closed by tomato42** 2019-09-29 17:44 UTC

**Comment by tomato42** [comment] 2019-09-29 18:02
regarding the "confused" emoji: see PR #118, check if it implements what you need

I don't know what encoding you want the public key in, but the hex encoding can be achieved like this:
```python
from ecdsa.keys import VerifyingKey
from ecdsa.curves import SECP256k1
key = # hex encoding of the key 
vk = VerifyingKey.from_string(bytes.fromhex(key), curve=SECP256k1)
pub_key = vk.to_string('uncompressed')
print(pub_key.hex())
```

(it won't work with your example key as it's incorrect size)

**Comment by NotStatilko** [comment] 2019-09-29 22:33
Thanks for your quick reply

I tried run this code with compressed public key 
```
03F028892BAD7ED57D2FB57BF33081D5CFCF6F9ED3D3D7F159C2E2FFF579DC341A
```
But it throws this error:

```
python3.7/site-packages/ecdsa/keys.py", line 37, in from_string                                       (len(string), curve.verifying_key_length)           AssertionError: (33, 64)
```

**Code:**
```
from ecdsa.keys import VerifyingKey
from ecdsa.curves import SECP256k1

key = '03F028892BAD7ED57D2FB57BF33081D5CFCF6F9ED3D3D7F159C2E2FFF579DC341A'
vk = VerifyingKey.from_string(bytes.fromhex(key), curve=SECP256k1)
pub_key = vk.to_string('uncompressed')

print(pub_key.hex())
```

Do you know what the problem is?

**Comment by tomato42** [comment] 2019-09-30 11:53
```
AssertionError: (33, 64)
```
you're not using the code from the PR #118

**Comment by NotStatilko** [comment] 2019-09-30 16:12
Thank you very much! It's really helps me a lot!

**Comment by NotStatilko** [comment] 2019-09-30 16:17
If anyone need, here is my code
```
class MalformedPoint(Exception):
    pass

from ecdsa.numbertheory import square_root_mod_prime
from ecdsa.util import string_to_number, number_to_string
from ecdsa.ellipticcurve import Point
from ecdsa.curves import SECP256k1
from ecdsa import ecdsa


def compress(x: int, y: int) -> bytes:
    e_x = number_to_string(x,SECP256k1.order) #encoded x
    return (b'\x03' + e_x) if y % 2 else (b'\x02' + e_x)


def uncompress(string: bytes, curve=SECP256k1) -> Point:
    if string[:1] not in (b'\x02', b'\x03'):
        raise MalformedPoint("Malformed compressed point encoding")
            
    is_even = string[:1] == b'\x02'
    x = string_to_number(string[1:])
    order = curve.order
    p = curve.curve.p()
    alpha = (pow(x, 3, p) + (curve.curve.a() * x) + curve.curve.b()) % p
    try:
        beta = square_root_mod_prime(alpha, p)
    except SquareRootError as e:
        raise MalformedPoint(
            "Encoding does not correspond to a point on curve", e
        )                                 
    if is_even == bool(beta & 1):
        y = p - beta
    else:
        y = beta
    if not ecdsa.point_is_valid(curve.generator, x, y):
        raise MalformedPoint("Point does not lie on curve")
    return Point(curve.curve, x, y, order)
```
