### ISSUE TITLE
How to sign with data and private key.

### ISSUE THREAD

**Issue by narnikgamarnikus** [warner/python-ecdsa#77] opened 2018-01-19 23:42 UTC
Hello.

In Go, there is a [library] (https://github.com/blockcypher/btcutils) that allows sign. But it takes 2 arguments, and yours - one.

I need the function to take 2 arguments, and I did not find any libraries in Python to do this.

Perhaps I'm in vain looking to you for this question, but perhaps you understand what I need.

**Comment by tomato42** [comment] 2018-01-21 20:14
`sign()` is method of `Private_key` object
to create `Private_key` you have to provide the private key

so exactly which part is the problem?

**Comment by tomato42** [comment] 2018-09-05 12:55
not a bug and no answer from requester, closing

**Closed by tomato42** 2018-09-05 12:55 UTC
Labels: not a bug
