### ISSUE TITLE
Import Very Slow on Raspberry Pi

### ISSUE THREAD

**Issue by om26er** [warner/python-ecdsa#211] opened 2020-11-07 19:06 UTC
On a Raspberry Pi, a simple import of ecdsa takes a lot of time, that results in very slow start for our software. In some cases, it can take as much as 30 seconds to import below
```
from ecdsa.curves import SECP256k1
```

During the import, the CPU stays at 100%.

We have tried it on multiple operating systems
  * Ubuntu Server 20.10
  * Yocto based custom image as well.

**Comment by om26er** [comment] 2020-11-07 19:12
* On a cold pycache it takes 30 seconds to import on the Pi.
* On future attempts it stays above 17 seconds for the import.

**Comment by oberstet** [comment] 2020-11-07 19:14
fwiw, here is a test on x86-64/pypy3:

![Bildschirmfoto von 2020-11-07 20-13-24](https://user-images.githubusercontent.com/233340/98449686-ca8aa800-2135-11eb-91c4-e49f9ce5e2a8.png)

**Comment by tomato42** [comment] 2020-11-07 20:39
duplicate of #180

**Closed by tomato42** 2020-11-07 20:39 UTC
