### ISSUE TITLE
Version 0.14 fails when importing from six

### ISSUE THREAD

**Issue by CMTaylor** [warner/python-ecdsa#160] opened 2019-11-06 21:54 UTC
Version 0.14 fails here: https://github.com/warner/python-ecdsa/blob/master/src/ecdsa/ellipticcurve.py#L37

I've tried the latest and 1 earlier versions of six. Both get this error:|
  File "...\lib\site-packages\ecdsa\__init__.py", line 1, in <module>
    from .keys import SigningKey, VerifyingKey, BadSignatureError, BadDigestError,\
  File "...\lib\site-packages\ecdsa\keys.py", line 72, in <module>
    from . import ecdsa
  File "...\lib\site-packages\ecdsa\ecdsa.py", line 57, in <module>
    from . import ellipticcurve
  File "...\lib\site-packages\ecdsa\ellipticcurve.py", line 37, in <module>
    from six import python_2_unicode_compatible
ImportError: cannot import name python_2_unicode_compatible

**Comment by tomato42** [comment] 2019-11-06 22:01
duplicate of #159, version 0.14.1 should fix it

**Closed by tomato42** 2019-11-06 22:01 UTC
